#!/usr/bin/env python3

#
# Copyright (C) 2026 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import yaml
import agent

module_id = os.environ['MODULE_ID']
agent_id = os.environ['AGENT_ID']
node_id = int(os.environ['NODE_ID'])

def main():
    global module_id, node_id
    targets = [{
        "targets": [f"127.0.0.1:{os.environ['TCP_PORT']}"],
        "labels": {
            "module_id": module_id,
            "node": node_id, # no "_id" suffix for Metrics
        },
    }]
    update_metrics(targets)

def update_metrics(targets):
    global module_id, agent_id
    trx = agent.redis_connect(privileged=True).pipeline()
    trx.hset(f"module/{module_id}/metrics_targets", "loki", yaml.dump(targets))
    trx.publish(f"{agent_id}/event/metrics-target-changed", "{}")
    trx.execute()

if __name__ == "__main__":
    main()
