#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

from datetime import datetime, timezone

import os
import json
import sys
import subprocess

# Cloud Log Manager

info = {
    "retention_days": int(os.getenv('LOKI_RETENTION_PERIOD')),
    "cloud_log_manager": "",
    "syslog": ""
}

clm_status = subprocess.run(['systemctl', '--user', 'is-active', 'cloud-log-manager-forwarder'], capture_output=True, text=True)
match clm_status.stdout.strip():
    case 'active':
        info["cloud_log_manager"] = 'active'
    case 'failed':
        info["cloud_log_manager"] = 'failed'
    case _:
        info["cloud_log_manager"] = 'inactive'


# Syslog

syslog_status = subprocess.run(['systemctl', '--user', 'is-active', 'syslog-forwarder'], capture_output=True, text=True)
match syslog_status.stdout.strip():
    case 'active':
        info["syslog"] = 'active'
    case 'failed':
        info["syslog"] = 'failed'
    case _:
        info["syslog"] = 'inactive'

json.dump(info, sys.stdout)
