#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#


import os
import json
import sys
import subprocess

# Cloud Log Manager

info = {
    "retention_days": int(os.getenv('LOKI_RETENTION_PERIOD')),
    "cloud_log_manager": subprocess.check_output(['systemctl', '--user', 'is-enabled', 'cloud-log-manager-forwarder']).strip(),
    "syslog": subprocess.check_output(['systemctl', '--user', 'is-enabled', 'syslog-forwarder']).strip(),
}
json.dump(info, sys.stdout)
