#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#


import os
import json
import sys
import subprocess

info = {
    "retention_days": int(os.getenv('LOKI_RETENTION_PERIOD')),
    "cloud_log_manager": subprocess.run(['systemctl', '--user', 'is-enabled', 'cloud-log-manager-forwarder'], check=False, capture_output=True).returncode == 0,
    "syslog": subprocess.run(['systemctl', '--user', 'is-enabled', 'syslog-forwarder'], check=False, capture_output=True).returncode == 0,
}
json.dump(info, sys.stdout)
