#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os

import agent

# Set environment variables
if os.getenv('LOKI_RETENTION_PERIOD') is None:
    agent.set_env('LOKI_RETENTION_PERIOD', '365d')
