name: Unit tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: ./test-unit.sh
